# Generated by Django 6.0.6 on 2026-07-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expenseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier_invoice', models.CharField(blank=True, max_length=100)),
                ('expense_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('CASH_TRANSFER', 'Cash + Transfer')], max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='api.expenseitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='api.supplier')),
            ],
        ),
    ]
