# Generated by Django 6.0.6 on 2026-07-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_expense_amount_remove_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='OldExpense',
        ),
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=30, unique=True)),
                ('purchase_date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='purchase_receipts/')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_invoice', models.CharField(blank=True, max_length=100)),
                ('cash_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.expenseitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.supplier')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchasevoucher')),
            ],
        ),
    ]
