# Generated by Django 6.0.6 on 2026-07-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_expense_oldexpense_purchasevoucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Cash/Transfer', 'Cash/Transfer')], default='Cash', max_length=20),
        ),
    ]
